In [ ]:
import numpy as np
import pandas as pd
import 

In [14]:
arr = np.array([12,3,4,5],ndmin=2)

In [ ]:
print(arr)
print(arr.ndim)
print(arr.shape)

[[12  3  4  5]]
2
(1, 4)


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([[[1],[1]],[[1],[1]]])

In [33]:
print(arr2)
print(arr2.shape)
print("dimesnerions are: ,",arr2.ndim)

[[[1]
  [1]]

 [[1]
  [1]]]
(2, 2, 1)
dimesnerions are: , 3


In [7]:
arr =np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])